#ifndef VITALSIGNSDLL_GLOBAL_H
#define VITALSIGNSDLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VITALSIGNSDLL_LIBRARY)
#  define VITALSIGNSDLLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define VITALSIGNSDLLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VITALSIGNSDLL_GLOBAL_H
